version: '3.9'

services:
  api:
    container_name: auth_server
    restart: always
    build: .
    networks:
      - auth-network

  nginx:
    container_name: auth_nginx
    restart: always
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - api
    networks:
      - auth-network

networks:
  auth-network:
    external: true
